# Generated by Django 3.0.3 on 2020-03-03 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_actdiarias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActDiarias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('desdeHora', models.TimeField()),
                ('hastaHora', models.TimeField()),
                ('observacionAdicional', models.CharField(default='', max_length=300)),
                ('porcentajeAvance', models.FloatField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Act')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Cliente')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Colab')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Servicio')),
            ],
        ),
    ]
