# Generated by Django 3.0.3 on 2020-03-03 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_actdiarias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='actdiarias',
            options={'verbose_name': 'Actividad diaria', 'verbose_name_plural': 'Actividades diarias'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='colab',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
